Jobeet\Finder\Domain\Model\Category\Category:
    type: entity
    table: category

    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    fields:
        name:
            type: string
            length: 255
            nullable: true
            unique: true

    oneToMany:
        jobs:
            orderBy: { 'expires_at': 'DESC' }
            targetEntity: Jobeet\Finder\Domain\Model\Job\Job
            mappedBy: category