imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ ]
    filters:
        cssrewrite: ~

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_sqlite
        charset:  UTF8
        path:     %database_path%

    orm:
        default_entity_manager:  default
        entity_managers:
            default:
                auto_mapping:         false
                mappings:
                    # An array of mappings, which may be a bundle name or something else
                    JobeetFinderBundle:
                        mapping:              true
                        type:                 yml
                        dir:                  Resources/config/doctrine
                        prefix:               Jobeet\Finder\Domain\Model
                        is_bundle:            true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }
